import test from 'node:test';
import XLSX from 'xlsx';
test('normal undisclosed fields remain notes, not review failures', async () => {
 const bridge = new QccHostBridge({tools:{get(){return {}},execute(){throw Error('must not call')}}});
 bridge.enrichCompany = async () => ({status:'enriched',fields:{},fieldIssues:{
   financial_total_revenue:{message:'未披露',reviewRequired:false}}});
 const result = await bridge.enrichRows([{name:'合成测试有限公司'}],{fieldSelection:['financial_total_revenue']});
 assert.equal(result.summary.enriched,1);
 assert.equal(result.summary.fieldReview ?? 0,0);
 assert.equal(result.rows[0].qcc_field_issues,'');
 assert.match(result.rows[0].qcc_field_notes,/未披露/);
 assert.equal(result.rows[0].financial_total_revenue,undefined);
});
test('batch field-review counts, terminal state and resolved issue cleanup remain consistent',async()=>{
 const {G5RunStore}=await import('../lib/qcc-runs.js');
 const bridge=new QccHostBridge({tools:{get(){return {}},execute(){throw Error('must not call')}}});
 bridge.enrichCompany=async()=>({status:'enriched',fields:{actual_controller_name:''},fieldIssues:{actual_controller_name:{message:'多名实际控制人，需人工核验'}}});
 const result=await bridge.enrichRows([{name:'合成测试有限公司'}],{fieldSelection:['actual_controller_name']});
 assert.equal(result.summary.enriched,0);assert.equal(result.summary.fieldReview,1);
 assert.match(result.rows[0].qcc_field_issues,/多名/);
 const store=new G5RunStore();
 const run=store.createRun({headers:['name'],nameField:'name',fieldSelection:['actual_controller_name'],result});
 assert.equal(run.state,'completed-with-errors');assert.equal(run.summary.fieldReview,1);
 const record=store.requireRun(run.runId);
 store.patchCompany(record,'合成测试有限公司',[0],{status:'enriched',fields:{actual_controller_name:'合成控制人甲'}});
 const resolved=store.snapshot(record);
 assert.equal(resolved.state,'completed');assert.equal(resolved.summary.fieldReview,0);
 assert.equal(resolved.summary.enriched,1);assert.equal(resolved.rows[0].qcc_field_issues,'');
});
test('controller issues stay visible in results/exception exports while unrelated values remain usable',async()=>{
 const {WorkflowArtifactStore}=await import('../lib/artifacts.js');
 const rows=[{企业名称:'合成测试有限公司',实控人:'',actual_controller_name:'',qcc_match_status:'enriched',qcc_field_issues:'actual_controller_name: 返回多名实际控制人，需人工核验'}];
 const memory=new Map();
 const store=new WorkflowArtifactStore({fs:{resolve:async key=>({key}),writeText:async(target,text)=>memory.set(target.key,Buffer.from(text)),readBytes:async target=>memory.get(target.key)},idFactory:(()=>{let n=0;return()=> 'dca-controller-'+(++n).toString().padStart(6,'0')})()});
 const artifacts=await store.createBundle('dcw-controller-001',{headers:['企业名称','实控人'],rows,fieldSelection:['actual_controller_name'],mappings:[{sourceField:'实控人',targetField:'actual_controller_name'}]});
 const csv=artifacts.find(a=>a.kind==='review'&&a.format==='xlsx');
 assert.ok(csv);
 const book=XLSX.read(await store.read('dcw-controller-001',csv),{type:'buffer'});
 const text=JSON.stringify(XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]));
 assert.match(text,/多名实际控制人/);
 assert.match(text,/字段补全待核验原因/);
 const projected=projectCompletionResult({headers:['企业名称','实控人'],rows:[{...rows[0],actual_controller_name:'合成控制人'}],fieldSelection:['actual_controller_name'],mappings:[{sourceField:'实控人',targetField:'actual_controller_name'}]});
 assert.equal(projected.rows[0].实控人,'合成控制人');
});
import assert from 'node:assert/strict';
import {ACTUAL_CONTROLLER_GROUP as group,projectActualController} from 'qcc-field-contracts';
import {QccHostBridge,QCC_TOOL_NAMES,estimateQccCalls,mapActualControllerFields} from '../lib/qcc.js';
import {QCC_FIELD_CATALOG} from '../lib/qcc-field-catalog.js';
import {projectCompletionResult} from '../lib/engine.js';
const data={企业名称:'合成测试有限公司',total_count:1,has_more:false,next_cursor:null,实际控制人信息:[{实际控制人名称:'合成人员甲',直接持股比例:'35.4938%',总持股比例:'47.6955%',表决权比例:'53%'}]};
const fields=group.fields.map(f=>f.id);
test('cleaning consumes shared controller contract and routes exactly one controller tool',async()=>{
 assert.equal(QCC_FIELD_CATALOG.find(g=>g.id===group.id),group);
 assert.deepEqual(estimateQccCalls(2,fields).sourceTools,['get_actual_controller']);
 assert.equal(estimateQccCalls(2,fields).estimatedCalls,4);
 const bridge=new QccHostBridge({tools:{get(){return {}},execute(){throw Error('unexpected transport')}}});const calls=[];
 bridge.call=async(name,args)=>{calls.push([name,args]);return {data}};
 const result=await bridge.enrichMatchedCompany({companyName:data.企业名称,creditNo:'SYNTHETIC'},{fieldSelection:fields});
 assert.deepEqual(result.fields,projectActualController(data).values);
 assert.deepEqual(calls.map(c=>c[0]),[QCC_TOOL_NAMES.actualController]);
 assert.throws(()=>mapActualControllerFields(data,{companyName:'另一合成有限公司'}),{code:'QCC_ENTITY_MISMATCH'});
 data.实际控制人信息.push({...data.实际控制人信息[0],实际控制人名称:'合成人员乙'});data.total_count=2;
 const multi=await bridge.enrichMatchedCompany({companyName:data.企业名称},{fieldSelection:fields});
 assert.equal(multi.fields.actual_controller_name,'');
 assert.equal(multi.fieldIssues.actual_controller_name.code,'multiple-controllers');
});
